apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: appapi
spec:
  selector:
    matchLabels:
      app: appapi
  replicas: 1
  template:
    metadata:
      labels:
        app: appapi
    spec:
      containers:
      - name: appapi
        image: local/api
        imagePullPolicy: Never
        ports:
        - name: api-service
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: appapi
  ports:
  - port: 3000
    targetPort: api-service